version: "3.9"

services:
  database:
    image: postgres:15.5-alpine
    container_name: "minhagenda_db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=minhagenda
      - POSTGRES_USER=minhagenda
      - POSTGRES_PASSWORD=minhagenda
