version: '3.9'

services:
  database:
    image: postgres:15.5-alpine
    container_name: 'postgres-development'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=minhagenda-development
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
