version: '3.9'

services:
  database:
    image: postgres:15.5-alpine
    container_name: 'minha-agenda-db'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=minha-agenda
      - POSTGRES_USER=minha-agenda
      - POSTGRES_PASSWORD=minha-agenda
